# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres:16.2
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - '5432:5432'
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: pomodoro

  adminer:
#    Adminer предоставляет удобный веб-интерфейс для работы с базой данных PostgreSQL. С его помощью вы можете:
#
#    Выполнять SQL-запросы.
#    Просматривать и редактировать данные в таблицах.
#    Управлять структурой базы данных (создание, изменение и удаление таблиц).
#    Импортировать и экспортировать данные.
#    Таким образом, Adminer является полезным инструментом для разработчиков и администраторов баз данных,
#    позволяя им легко взаимодействовать с базой данных без необходимости использования командной строки.
    image: adminer
    restart: always
    ports:
      - 8080:8080

#  portainer:
#    image: portainer/portainer-ce
#    restart: always
#    ports:
#      - '9000:9000'
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - portainer_data:/data
#
#volumes:
#  portainer_data:


  redis:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - '6379:6379'